# Generated by Django 4.2.3 on 2023-07-13 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2)], verbose_name='Title')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('genre', models.CharField(choices=[('Action and Adventure Fiction', 'Action and Adventure Fiction'), ('Classic Fiction', 'Classic Fiction'), ('Contemporary Fiction', 'Contemporary Fiction'), ('Dystopian Fiction', 'Dystopian Fiction'), ('Fantasy Fiction', 'Fantasy Fiction'), ('Graphic Novel', 'Graphic Novel'), ('Historical Fiction', 'Historical Fiction'), ('Horror Fiction', 'Horror Fiction'), ('LGBTQ+ Fiction', 'LGBTQ+ Fiction'), ('Literary Fiction', 'Literary Fiction'), ('Mystery Fiction', 'Mystery Fiction'), ('Romance Fiction', 'Romance Fiction'), ('Satire Fiction', 'Satire Fiction'), ('Science Fiction', 'Science Fiction'), ('Short Story', 'Short Story'), ('Thriller Fiction', 'Thriller Fiction'), ('Utopian Fiction', 'Utopian Fiction'), ('Western Fiction', 'Western Fiction'), ('Women’s Fiction', 'Women’s Fiction'), ('Young Adult', 'Young Adult'), ('Nonfiction genres', 'Nonfiction genres'), ('Art and Photography', 'Art and Photography'), ('Biography', 'Biography'), ('Cookbooks', 'Cookbooks'), ('Historical Nonfiction', 'Historical Nonfiction'), ('How-to and DIY', 'How-to and DIY'), ('Humor', 'Humor'), ('Memoir and Autobiography', 'Memoir and Autobiography'), ('Parenting', 'Parenting'), ('Philosophy', 'Philosophy'), ('Religion and Spirituality', 'Religion and Spirituality'), ('Self-Help', 'Self-Help'), ('Travel', 'Travel'), ('True Crime', 'True Crime')], verbose_name='Genre')),
                ('publication_date_book', models.DateField(verbose_name='Book Publication Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksFaceApp.author', verbose_name='Author')),
            ],
        ),
    ]
