# Generated by Django 4.2.3 on 2023-07-13 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URl')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reviews_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Reviews'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BooksFaceApp.publisher', verbose_name='Publisher'),
        ),
    ]
