# Generated by Django 4.2.3 on 2023-07-13 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0002_publisher_book_reviews_counter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews_counter',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reviews'),
        ),
        migrations.CreateModel(
            name='ReviewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Review')),
                ('grade', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Book Grade')),
                ('review_date', models.DateTimeField(verbose_name='Review Publishing Time')),
                ('likes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Review Likes')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='BooksFaceApp.book', verbose_name='Book')),
            ],
        ),
    ]
