# Generated by Django 4.2.3 on 2023-07-26 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0004_alter_reviewbook_book_alter_reviewbook_grade_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_by',
            field=models.CharField(default=None, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.CharField(default=None, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='City/Town/Village'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='password', validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password Confirmation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_by',
            field=models.CharField(default=None, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date_book',
            field=models.DateField(blank=True, null=True, verbose_name='Book Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BooksFaceApp.publisher', verbose_name='Publisher'),
        ),
    ]
