# Generated by Django 4.2.3 on 2023-07-31 08:13

import BooksFace.BooksFaceApp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0005_author_created_by_book_created_by_profile_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='image_url',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(3000)], verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The first name of the author must start with a capital letter!')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The last name of the author must start with a capital letter!')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_counter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(120), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The book title must start with a capital letter!')], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The name of the  city/town/village must start with a capital letter!')], verbose_name='City/Town/Village'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default=None, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text="The country's name must start with a capital letter!")], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The first name must start with a capital letter!')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The last name must start with a capital letter!')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8), BooksFace.BooksFaceApp.validators.check_password_capital_letter, BooksFace.BooksFaceApp.validators.check_password_lowercase_letter, BooksFace.BooksFaceApp.validators.check_password_special_symbol, BooksFace.BooksFaceApp.validators.check_password_number], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='password', verbose_name='Password Confirmation'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The name of the publisher must start with a capital letter!')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Publisher Website'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Review Likes'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='review',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Review Publishing Time'),
        ),
    ]
