# Generated by Django 4.2.3 on 2023-08-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0006_remove_book_image_url_remove_publisher_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-reviews_counter', 'title']},
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='Birth Country'),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(unique=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='BooksFaceApp.book', verbose_name='Book'),
        ),
    ]
