# Generated by Django 4.2.3 on 2023-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0007_alter_book_options_author_country_author_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, null=True, verbose_name='City'),
        ),
    ]
