# Generated by Django 4.2.3 on 2023-08-01 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0008_remove_author_nationality_author_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.MaxLengthValidator(3000)], verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Birth Country'),
        ),
    ]
