# Generated by Django 4.2.3 on 2023-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0009_author_birthday_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='author',
            name='dead',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Died on'),
        ),
    ]
