# Generated by Django 4.2.3 on 2023-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0010_alter_author_options_author_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Nickname'),
        ),
    ]
