# Generated by Django 4.2.3 on 2023-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0011_author_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Nationality'),
        ),
    ]
