# Generated by Django 4.2.3 on 2023-08-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0012_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='ceo',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Central Country'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Central Country'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='founded',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='Founded on'),
        ),
    ]
