# Generated by Django 4.2.3 on 2023-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0014_publisher_closed_alter_publisher_ceo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.AddField(
            model_name='publisher',
            name='office',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Office'),
        ),
    ]
