# Generated by Django 4.2.3 on 2023-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0017_alter_book_publisher_alter_reviewbook_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbook',
            name='author',
            field=models.CharField(verbose_name='Review Author'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='BooksFaceApp.book', verbose_name='Book'),
        ),
    ]
