# Generated by Django 4.2.3 on 2023-08-04 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0018_alter_reviewbook_author_alter_reviewbook_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewbook',
            options={'ordering': ['review_date']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(2)], verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
