# Generated by Django 4.2.3 on 2023-08-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0019_alter_reviewbook_options_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
