# Generated by Django 4.2.3 on 2023-08-04 15:20

import BooksFace.BooksFaceApp.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BooksFaceApp', '0020_remove_profile_first_name_remove_profile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The first name must start with a capital letter!')], verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(2), BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The last name must start with a capital letter!')], verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
