# Generated by Django 4.2.3 on 2023-08-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0021_remove_profile_last_login_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
