# Generated by Django 4.2.3 on 2023-08-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0024_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
