# Generated by Django 4.2.3 on 2023-08-05 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0030_remove_book_likes_alter_book_genre_alter_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbook',
            name='likes',
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Book Grade'),
        ),
    ]
