# Generated by Django 4.2.3 on 2023-08-11 15:29

import BooksFace.BooksFaceApp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0031_remove_reviewbook_likes_alter_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=None, validators=[BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The first name must start with a capital letter!'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(150)], verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=None, validators=[BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The last name must start with a capital letter!'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(150)], verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
