# Generated by Django 4.2.3 on 2023-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0033_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_by',
            field=models.CharField(editable=False, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.CharField(editable=False, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_counter',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created_by',
            field=models.CharField(editable=False, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='author',
            field=models.CharField(editable=False, verbose_name='Review Author'),
        ),
    ]
