# Generated by Django 4.2.3 on 2023-08-14 09:24

import BooksFace.BooksFaceApp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0036_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(validators=[BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The first name must start with a capital letter!'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(150)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(validators=[BooksFace.BooksFaceApp.validators.CheckStartsWithCapitalLetter(text='The last name must start with a capital letter!'), django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(150)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(verbose_name='Username'),
        ),
    ]
