# Generated by Django 4.2.3 on 2023-08-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksFaceApp', '0038_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
